# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael England
title: Software Engineer
website: mikeengland.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mikeengland
stackoverflow_username: "1224372"
linkedin_username: michaelengland91

# Additional icon links
# additional_links:
- title: Medium blog
  icon: fa-brands fa-medium
  url: https://medium.com/@michael_england


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Mike. I'm a software engineer with 10+ years of experience across multiple different industries. During this time I have worked as both an individual contributor and have managed engineering teams. I have experience building large scale applications, working across front-end and back-end technology stacks. I also have DevOps/platform engineering experience, building out big data and cloud infrastructure for a variety of use cases.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: django-setty
        link: github.com/mikeengland/django-setty
        quote: >
          Django-Setty allows you to dynamically change settings inside the Django Admin Console. The app provides both a database and a cache backend for storing and retrieving your settings.
        description: |
          This was a Django module I worked on as a side project in my spare time
      - layout: top-middle
        title: pypika
        link: github.com/kayak/pypika
        quote: >
          PyPika is a Python API for building SQL queries. The motivation behind PyPika is to provide a simple interface for building SQL queries without limiting the flexibility of handwritten SQL. Designed with data analysis in mind, PyPika leverages the builder design pattern to construct queries to avoid messy string formatting and concatenation. It is also easily extended to take full advantage of specific features of SQL database vendors.
        description: |
          I worked on the popular open source PyPika module during my years working for KAYAK. This is used in many projects, both public and private. Netflix [even built a framework on top of it](https://netflixtechblog.com/python-at-netflix-bba45dae649e).
      - layout: top-middle
        title: fireant
        link: github.com/kayak/fireant
        quote: >
          fireant is a a data analysis tool used for quickly building charts, tables, reports, and dashboards. It defines a schema for configuring metrics and dimensions which removes most of the leg work of writing queries and formatting charts. fireant even works great with Jupyter notebooks and in the Python shell providing quick and easy access to your data.
        description: |
          I worked on the open source fireant module during my years working for KAYAK.

  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Loughborough University
        caption: 2009 - 2013
        sub_title: BSc Computing and Management
        description: |
          I achieved a First Class Honours degree in Computing and Management and a Diploma in Professional Studies.

  # - title: A Little More About Me
  #   layout: text
  #   content: |
  #     Alongside my interests in software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
