# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael England
title: Software Engineer
website: mikeengland.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mikeengland
stackoverflow_username: "1224372"
linkedin_username: michaelengland91

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mike. I'm a Software Engineer with 10+ years of experience across multiple different industries. During this time I have worked as both an individual contributor and have managed Engineering teams. I have experience building large scale applications, working across front-end and back-end technology stacks. I also have DevOps experience, building out big data and cloud infrastructure for a variety of use cases.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: django-setty
        link: github.com/mikeengland/django-setty
        quote: >
          Django-Setty allows you to dynamically change settings inside the Django Admin Console. The app provides both a database and a cache backend for storing and retrieving your settings.

  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Loughborough University
        caption: 2009 - 2013
        sub_title: BSc Computing and Management
        description: |
          I achieved a First Class Honours degree in Computing and Management and a Diploma in Professional Studies.I achieved a First Class Honours degree in Computing and Management and a Diploma in Professional Studies.

  # - title: A Little More About Me
  #   layout: text
  #   content: |
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
