# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael England
title: Software Engineer
website: mikeengland.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mikeengland
linkedin_username: michaelengland91

# Additional icon links
additional_links:
- title: Medium blog
  icon: fab fa-medium
  url: https://medium.com/@michael_england


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Mike. I'm a software engineer with 10+ years of experience across multiple different industries. During this time I have worked as both an individual contributor and have managed engineering teams. I have experience building large scale applications, working across front-end and back-end technology stacks. I also have DevOps/platform engineering experience, building out big data and cloud infrastructure for a variety of use cases.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: NatWest Group (London, UK)
        link: www.natwestgroup.com
        sub_title: Software Engineer
        caption: 2021 - present
        quote: ML Engineering team
        description: | 
          Currently working in the Data Science & Innovation ML Engineering team, moving data science workloads to AWS.
      - layout: left
        title: KAYAK         (Berlin, Germany)
        link: www.kayak.com
        sub_title: Software Engineer | Senior Software Engineer | Engineering Team Lead
        caption: 2015-2021
        quote: >
          Working on performance marketing and data analytics problems
        description: |
          I joined KAYAK as a software engineer working on a new in-house ad bidding application for performance marketing. This expanded
          quickly to become a fully fledged marketing platform, comprising of not just ad bidding for all major marketing platforms, 
          integrating advanced algorithm/model management for data scientists, but also sophisticated content creation and feed management features. 
          Later, I worked on a new in-house Business Intelligence application, now used by thousands of users across OpenTable and KAYAK. 
          By the time I left the company, I was leading a successful engineering team and was responsible for the development of both applications.

          Technologies used: Python, Django, React.js, JavaScript, TypeScript, MySQL, Vertica, Redis, Snowflake, MongoDB, Docker
      - layout: left
        title: Nomura (London, UK)
        link: www.nomura.com
        sub_title: Technology Analyst | Senior Infrastructure Engineer
        caption: 2013-2015
        quote: >
          Working in Nomura's infrastructure division
        description: |
          During my time at Nomura I worked on the deployment of Big Data and NoSQL software, notably Hadoop and MongoDB. 
          I was assigned as the organisation's subject matter expert on Hadoop, and led numerous application POCs and deployments.
          Additionally, I worked on building out a new API framework focused on infrastructure automation. This project became the basis
          for Nomura's self-serve infrastructure and automated alert remediation.

          Technologies used: Python, Flask, JavaScript, Java, Memcached, MySQL, ActiveMQ, Hadoop (MapR, Cloudera, Hortonworks), Tibco EMS
      - layout: left
        title: Nomura (London, UK)
        link: www.nomura.com
        sub_title: Industrial Placement Student 
        caption: 2011-2012
        quote: >
          Industrial Placement in Nomura's infrastructure divison
        description: |
          My Industrial Placement at Nomura consisted of two rotations across the Oracle DBA and Web Engineering teams.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: django-setty
        link: github.com/mikeengland/django-setty
        quote: >
          Django-Setty allows you to dynamically change settings inside the Django Admin Console. The app provides both a database and a cache backend for storing and retrieving your settings.
        description: |
          This was a neat Django module I worked on as a side project in my spare time.
          The motivation for building this was handling live configuration inside of Django without using external
          dependencies such as Zookeeper.
      - layout: left
        title: PyPika
        link: github.com/kayak/pypika
        quote: >
          PyPika is a Python API for building SQL queries. The motivation behind PyPika is to provide a simple interface for building SQL queries without limiting the flexibility of handwritten SQL. Designed with data analysis in mind, PyPika leverages the builder design pattern to construct queries to avoid messy string formatting and concatenation. It is also easily extended to take full advantage of specific features of SQL database vendors.
        description: |
          I worked on the popular open source PyPika module during my years working for KAYAK. 
          This is used in many projects, both public and private, including some larger frameworks. Netflix [even built a framework on top of it](https://netflixtechblog.com/python-at-netflix-bba45dae649e).
      - layout: left
        title: Fireant
        link: github.com/kayak/fireant
        quote: >
          fireant is a a data analysis tool used for quickly building charts, tables, reports, and dashboards. It defines a schema for configuring metrics and dimensions which removes most of the leg work of writing queries and formatting charts. fireant even works great with Jupyter notebooks and in the Python shell providing quick and easy access to your data.
        description: |
          I worked on the open source Fireant module during my years working for KAYAK.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Loughborough University
        caption: 2009 - 2013
        sub_title: BSc Computing and Management
        description: |
          I achieved a First Class Honours degree in Computing and Management and a Diploma in Professional Studies.

  # - title: A Little More About Me
  #   layout: text
  #   content: |
  #     Alongside my interests in software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
